# Generated by Django 4.2.2 on 2023-07-02 13:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ca', 'cashier'), ('wa', 'waiter'), ('cu', 'customer')], default='cu', max_length=2)),
                ('password', models.CharField(max_length=20, validators=[accounts.models.validate_password])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
