# Generated by Django 4.2.2 on 2023-06-27 04:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ca', 'cashier'), ('cu', 'customer')], default='cu', max_length=2)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_is_staff', models.BooleanField(default=False)),
                ('user_is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, validators=[accounts.models.validate_password])),
                ('user_image_src', models.CharField(max_length=250)),
                ('birth_date', models.DateField(validators=[accounts.models.validate_birth_date])),
            ],
        ),
    ]
