# Generated by Django 4.2.2 on 2023-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
