# Generated by Django 4.2.2 on 2023-06-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
